### ISSUE TITLE
Cannot find name 'IDBKeyRange'

### ISSUE THREAD

**Issue by andraaspar** [palantir/eclipse-typescript#210]
I'm getting this with the folowing version:
  TypeScript    1.3.0.v20141121-1938    com.palantir.typescript.feature.feature.group   Palantir Technologies, Inc.

The code that produces this:
IDBKeyRange.bound(3, 5)

The project compiles fine with TypeScript 1.3.

Maybe this is because of an outdated lib.d.ts?
